name: CustomArcheology
authors: ['rzt1020', 'PQguanfang']
version: '${project.version}'
depend:
  - ProtocolLib
softdepend:
  - ItemsAdder
  - Oraxen
  - MythicMobs
  - eco
  - MMOItems
  - PlaceholderAPI
  - BetterStructures
  - MythicDungeons
  - NeigeItems
  - EcoItems
  - EcoArmor
  - ExecutableItems

main: cn.myrealm.customarcheology.CustomArcheology
api-version: '1.20'
commands:
  customarcheology:
    description: CustomArcheology Main Command
    usage: /customarcheology
    aliases: [ca, archeology]

permissions:
  customarcheology.*:
    default: op
    children:
      customarcheology.command.*: true
      customarcheology.play.*: true
  customarcheology.command.*:
    default: op
    children:
      customarcheology.command.help: true
      customarcheology.command.give: true
      customarcheology.command.reload: true
      customarcheology.command.archify: true
      customarcheology.command.dearchify: true
  customarcheology.command.help:
    default: op
  customarcheology.command.reload:
    default: op
  customarcheology.command.give:
    default: op
  customarcheology.command.archify:
    default: op
  customarcheology.command.dearchify:
    default: op
  customarcheology.play.*:
    default: true
    children:
      customarcheology.play.archeology: true
      customarcheology.play.highlight: false
  customarcheology.play.archeology:
    default: true
  customarcheology.play.highlight:
    default: op